plugins {
    id 'java'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

group 'com.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Asegúrate de usar versiones compatibles de Karate
    testImplementation 'com.intuit.karate:karate-junit5:1.4.1'
    testImplementation 'com.intuit.karate:karate-core:1.4.1'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
    testImplementation 'net.masterthought:cucumber-reporting:5.8.1'
}

sourceSets {
    test {
        resources {
            // Incluir recursos de test de ambas ubicaciones
            srcDirs = ['src/test/java', 'src/test/resources']
        }
    }
}

// Configurar estrategia para manejar archivos duplicados
tasks.withType(ProcessResources) {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

test {
    useJUnitPlatform()
    // Configuración para mostrar el resultado de los tests en la consola
    testLogging {
        events "passed", "skipped", "failed"
        showStandardStreams = true
    }
    // Configuración para generar informes de Karate
    systemProperty "karate.options", System.properties.getProperty("karate.options")
    systemProperty "karate.env", System.properties.getProperty("karate.env", "local")
    outputs.upToDateWhen { false }
}
